### ISSUE TITLE
Build - instance pending 

### ISSUE THREAD

**Issue by balasgit** [cloud-native-toolkit/terraform-gitops-cp-apic#8]
Build instance pending for more than 46 min 

Waiting for apiconnectclusters.apiconnect.ibm.com to come up in gitops-cp-apic
Waiting for apiconnectclusters.apiconnect.ibm.com to come up in gitops-cp-apic

https://github.com/cloud-native-toolkit/terraform-gitops-cp-apic/runs/6514757303?check_suite_focus=true

**Comment by gowdhaman-j** [comment]
The Common services issue was a major issue since Last Friday. Most of the CP4i Components wouldn't have worked

**Comment by vksuktha** [comment]
Is there an issue which we can track ?

**Comment by balasgit** [comment]
I have tested other CP4I modules like MQ, APP connect, Aspera which are all working ( assume it uses common services too). Here are build workflow actions

1. https://github.com/cloud-native-toolkit/terraform-gitops-cp-app-connect/actions
2. https://github.com/cloud-native-toolkit/terraform-gitops-cp-mq/actions
3. https://github.com/cloud-native-toolkit/terraform-gitops-cp-aspera-operator/actions

**Comment by balasgit** [comment]
As per @gowdhaman-j , APIC needs platform navigator dependency which @seansund working to resolve it. Will retest this, after PN released

**Comment by balasgit** [comment]
Issue is fixed by developers. Hence closing the issues
